apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops

labels:
  - pairs:
      cluster: qa-dc2

resources:
  - bootstrap
  - operator.yaml
  - operator-instance.yaml

components:
  - ../../groups/all
  - ../../groups/platform
  - ../../groups/qa
  - ../../groups/dc2

patches:
  - path: patch-app-a.yaml
