apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops

labels:
  - pairs:
      cluster: prod-dc2

resources:
  - bootstrap

components:
  - ../../groups/all
  - ../../groups/platform
  - ../../groups/prod
  - ../../groups/dc2

patches:
  - path: patch-app-a.yaml
