apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-operators
resources:
  - https://github.com/redhat-cop/gitops-catalog.git/openshift-pipelines-operator/overlays/latest?ref=main
  - resource-checker
