apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-c
resources:
  - ../../remote-base
configMapGenerator:
  - name: config
    behavior: merge
    literals:
      - app=app-c
      - test=change
