apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops

labels:
  - pairs:
      cluster: prod-dc1

resources:
  - bootstrap
  - operator.yaml
  - operator-instance.yaml

components:
  - ../../groups/all
  - ../../groups/platform
  - ../../groups/prod
  - ../../groups/dc1

patches:
  - path: patch-app-a.yaml
