apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops

labels:
  - pairs:
      env: prod
      dc: dc1
      cluster: prod-dc1

resources:
  - applications
  - bootstrap
