apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-pipelines
resources:
  - https://github.com/redhat-cop/gitops-catalog.git/openshift-pipelines-tasks/s2i-binary-build/base?ref=main
components:
  - components/api-v1
