apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-dc1-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/tom-stockwell/cluster-config-poc.git
    targetRevision: HEAD
    path: 2-applicationset-app-overlays/clusters/prod-dc1
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
