apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-a
  labels:
    app: app-a
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tom-stockwell/cluster-config-poc.git
    targetRevision: HEAD
    path: apps/app-a/overlays/<cluster>
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
